### ISSUE TITLE
Serialization of Dictionary<enum, string>

### ISSUE THREAD

**Issue by svantreeck** [JiyongShi/Best.AvroEx#1]
Hi, I'm wondering if there is any way to add a surrogate or modify how a property gets serialized so I could support serialization of a `Dictionary<MyEnum, string>`  into a map (or whatever the equivalent of Dictionary<string,string> is in this library/Avro).

Thanks

**Comment by JiyongShi** [comment]
avpr protocol limit Dictionary/Map's key must string, for multi language support, now not support Dictionary with key is not in string type.
